title:       "GitHub Page Template"
version:     "0012---19-Jul-2021"
copyright:   "2021-2021"
description: >- 
  This is a
  GitHub Page Template
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: ""
author:           "M.K Adit"
address:          "Tole Iskandar, Depok."
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https:/mkadit.github.io/os212"
urlcontact:       "TBA"
urlgithub:        "https://github.com/mkadit/os212"
urlghpage:        "https:/mkadit.github.io/os212"
keywords:         "jekyll, testing"
github:           [metadata]

